### ISSUE TITLE
Could not find file

### ISSUE THREAD

**Issue by bmiki** [codesharp-hu/szamlazz-hu-sdk#2]
Szia Gábor!

Nagyon köszönöm, hogy feltetted ezt a plugint. Sokat segített nekem. Egy nopCommerce webshopban használom.

Eddig kipróbáltam a számla létrehozásához használt interfészt.

Az alábbi sorban kapok egy exceptiont:

`response = await api.CreateInvoice(request);`

Az exception message az alábbi:
{"Could not find file 'createInvoiceRequest.sbn"}

A callstack:
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at System.IO.File.ReadAllText(String path)
   at SzamlazzHu.XMLRenderer.RenderRequest(CreateInvoiceRequest request)
   at SzamlazzHu.SzamlazzHuApi.<CreateInvoice>d__0.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Nop.Plugin.Payments.SzamlazzHu.SzamlazzHuPaymentProcessor.<ProcessPaymentAsync>d__11.MoveNext() in SzamlazzHuPaymentProcessor.cs:line 121

Üdv
Miki

**Comment by bmiki** [comment]
Letöltöttem a forrást és odamásoltam az .sbn fájlt a projekt mellé. Így már működik :)

**Comment by agabor** [comment]
Szia Miki!

Köszönöm a visszajelzést. Valóban kimaradtak az sbn fájlok a nuget csomagból. Átmenetileg jó úgy, hogy mellémásolod a fájlt. Ha törölni is szeretnél számlát vagy számlaadatot kérnél le, akkor a másik két sbn fájlra is szükséged lesz.

Üdv,
Gábor

**Comment by agabor** [comment]
Szia Miki!

Köszönöm a türelmet. Az 1.2.0-ás verzióban javítottam a hibát, ami nuget-ről letölthető.

**Comment by bmiki** [comment]
Szia Gábor!

Köszi, hogy feltetted.

Tegnap találtam még 1 hibát is, ami a legutóbbi kifizetesek tag-el
kapcsolatos kiterjesztésemben van.
Ez pedig az, hogy a <kifizetések> szekció nem mindig van jelen a
GetInvoiceResponse-ban. Csak akkor ha történt kifizetés. Viszont a kód
hibára fut, ha nincs benne kifizetés.
Már feltettem a javítást a github-ra a te repod forkoltam ide. Fogok
küldeni a héten pull requestet is erről.
Azért nem küldtem még mert szeretnék egy olyan fgv.-t is írni az API-ba ami
hibás response esetén exception-t dob.
Így lehetne választani, hogy hibakódot akar kezelni a kliens, vagy
exception-t akar kapni. Ez még nincs kész a héten akarom megírni.

Üdv
Miki

Gábor Angyal ***@***.***> ezt írta (időpont: 2021. máj. 31.,
H, 6:52):

**Comment by agabor** [comment]
Szia Miki!

Igen, ezt én is észrevettem, és írtam is rá egy javítást:
https://github.com/codesharp-hu/szamlazz-hu-sdk/commit/8ecb45ba0b82bec94d6c136dfbc7f7abab92d84a

Ez a javítás szintén bent van a nuget-en elérhető verzióban.

**Comment by bmiki** [comment]
Szuper! Köszi!

Gábor Angyal ***@***.***> ezt írta (időpont: 2021. máj. 31.,
H, 12:58):
